/** Operator-facing hints for `/config`. Fallback is the catalog `description` if a key is new. */
export const CONFIG_HINTS: Record<string, string> = {
    "dev.email.console_enabled": "Açıkken e-posta gönderilmez; alıcı, şablon ve link API konsoluna basılır. Kapatınca prod gibi Postmark'la gider. Yalnız stage/dev'de görünür.",
    "storage.upload.active_per_user": "Kullanıcı başına aynı anda kaç yükleme bileti veya akışı açık kalabilir.",
    "storage.upload.daily_bytes": "Kullanıcının gün içinde (UTC) yükleyebileceği bayt tavanı. Başarısız yükleme de rezervi yer.",
    "storage.upload.ticket_seconds": "Tek kullanımlık yükleme biletinin saniye cinsinden ömrü.",
    "storage.upload.stream_seconds": "Yetkili yükleme akışının en uzun süresi, saniye.",
    "payments.web.enabled": "Öğrenci planında web ödemesini açar. Kapalıyken yeni checkout reddedilir; açık abonelik durmaz.",
    "payments.mobile.enabled": "Öğrenci planını App Store / Google Play üzerinden satar. Web fiyatı mağaza fiyatıyla aynı olmalı.",
    "payments.web.redirect_to_mobile": "Web ödeme kapalıyken mağaza butonlarını gösterir. Yalnız mağaza kanalı açık kitlede işe yarar.",
    "promotions.enabled": "Kampanyaları açar. Kapalıyken her ödeme liste fiyatıdır.",
    "promotions.max_percent": "Tek indirimin liste fiyatına göre tavan yüzdesi. Sabit tutarlı kuponu da keser.",
    "promotions.max_discount_periods": "İndirimin kaç tahsilatı kapsayacağı. Çok dönemli fiyat yoksa 1 bırak.",
    "ads.enabled": "Tüm reklamları açar.",
    "ads.display.enabled": "Bağlama göre gösterilen reklam envanterini açar.",
    "ads.rewarded.enabled": "İsteğe bağlı ödüllü reklamı açar.",
    "ads.placement.knowledge_article_end.enabled": "Bilgi yazısının sonundaki tek reklam alanını açar.",
    "ads.placement.dashboard_rewarded_coin.enabled": "Paneldeki isteğe bağlı Coin ödülü teklifini açar.",
    "ads.rewarded.web.reward_coin": "Tamamlanan bir web reklamı için verilen Coin.",
    "ads.rewarded.web.daily_limit": "Kullanıcının günde tamamlayabileceği ödüllü reklam sayısı.",
    "ads.rewarded.web.cooldown_seconds": "İki ödüllü reklam arasındaki bekleme, saniye.",
    "ads.rewarded.web.session_ttl_seconds": "Ödül oturumunun ömrü, saniye.",
    "ads.rewarded.web.rollout_percent": "Ücretsiz kullanıcılara sabit hash ile açılma yüzdesi.",
    "ai.enabled": "Tüm yapay zekâ özelliklerini açar. Kapalıyken hiçbir AI çalışmaz.",
    "economy.enabled": "Hafif ekonomiyi açar: bakiye, hak kazanımı, kullanıcı yüzü.",
    "economy.streak_rescue.enabled": "Coin ile seri dondurmayı açar.",
    "community.leaderboard.enabled": "XP emek panosunu gösterir. Kişisel XP her zaman durur.",
    "forum.enabled": "Topluluğu açar: odalar, tartışmalar, moderasyon.",
    "community.achievements.enabled": "Kalıcı başarıları, kutlamayı ve başarı bildirimlerini açar.",
    "forum.coach_bridge.enabled": "Topluluk tartışmasından kişisel koça giden, PII'siz köprüyü açar.",
    "identity.google_oauth.enabled": "Google ile girişi açar. Ortamda GOOGLE_OAUTH_* olmalı.",
    "signup.enabled": "Yeni kaydı açar. Kapalıyken kayıt formu reddeder.",
    "coaching.preference_simulation.enabled": "Ücretsiz YKS 3D kampüs ve tercih karşılaştırması betasını açar.",
    "coaching.study_rooms.enabled": "Seans ekranındaki davet kodlu çalışma masalarını açar.",
    "mentorship.enabled": "İnsan koç yüzeyini açar: kadro, davet kodu, eşleme. Kapalıyken W8 uçları 403 döner.",
    "mentorship.followups.enabled": "Koç takip kaydı ve paylaşılan kararları açar.",
    "mentorship.weekly_reports.enabled": "Bitmiş hafta koç raporunu, AI bulgularını ve yazdırılabilir öğrenci görünümünü açar.",
    "mentorship.coach.max_active_students": "Koç başına aktif öğrenci tavanı. Davet kodu suistimal sınırı da budur. Ücretsiz koltuk sayısı ayrı.",
    "mentorship.seats.sponsorship_enabled": "Koçun sponsorlu Premium vermesini açar. Koç yüzeyi bundan bağımsız açılabilir.",
    "mentorship.seats.billing_enabled": "Koç koltuk planında web ödemesini açar. Kapalıyken ve mağaza da kapalıysa katalogda görünmez.",
    "mentorship.seats.mobile_billing_enabled": "Koç koltuk planını mağazadan satar. Web ödeme kapalıyken de listeler; fiyat mağazayla aynı olmalı.",
    "mentorship.coach.free_seats": "Koçun kaç öğrencisine ücretsiz Premium sponsorlanır. Koç × bu sayı = LLM maliyeti. 0 sponsorluğu durdurur.",
    "mentorship.invite_code.ttl_days": "Koç davet kodunun kaç gün geçerli kalacağı.",
    "mentorship.risk.inactive_days": "Seans veya bitmiş görev olmayınca öğrencinin INACTIVE sayılacağı gün.",
    "mentorship.risk.plan_completion_floor": "Son haftanın plan görevlerinden tamamlanan pay (0–1). Altı PLAN_SLIPPING işaretler.",
    "mentorship.risk.low_mood_ceiling": "Haftalık ortalama ruh hali (1–5). Bu değer ve altı LOW_MOOD işaretler.",
    "mentorship.risk_digest.enabled": "Koça günlük risk özetini (uygulama + e-posta) açar. Koç yüzeyinden bağımsızdır.",
    "mentorship.risk_digest.repeat_after_days": "Aynı riskin yeniden mail edilmeden önce sessiz kalacağı gün. Düşürmek bir sonraki koşuda herkese postalayabilir.",
    "mentorship.applications.open": "Koç kaydını herkese açar. Koç yüzeyinden bağımsız musluk; kapatınca yeni kayıt durur.",
    "mentorship.attention.ttl_days": "Koçun «ilgilendim» işaretinin ihtiyaç sayacından ve günlük özette kaç gün duracağı.",
    "identity.verification_email.resend_limit": "Doğrulama penceresinde kullanıcı başına en fazla kaç doğrulama maili gider.",
    "identity.verification_email.resend_window_seconds": "Doğrulama maili hız sınırının penceresi, saniye.",
    "identity.verification_email.token_ttl_seconds": "Doğrulama linkinin ömrü, saniye.",
    "notifications.jobs.poll_interval_seconds": "API örneklerinin bekleyen bildirim/e-posta işini kaç saniyede bir yokladığı.",
    "notifications.push.max_subscriptions": "Kullanıcı başına saklanan tarayıcı push kaydı tavanı.",
    "notifications.push.request_timeout_ms": "Push DNS veya sağlayıcı teslimatı için azami süre, milisaniye.",
    "economy.coin.daily_cap": "Kullanıcının günde kazanabileceği Coin tavanı.",
    "economy.coin.weekly_cap": "Kullanıcının haftada kazanabileceği Coin tavanı.",
    "economy.coin.min_xp_for_coin": "Coin kazanmak için gereken asgari XP.",
    "economy.invite.reward_coin": "Davet edilen kullanıcı dönüşünce davet edene verilen Coin.",
    "economy.quest.onboarding_reward_coin": "Tamamlanan her onboarding görevi için Coin.",
    "economy.quest.daily_ritual_reward_xp": "Tamamlanan her günlük ritüel görevi için XP.",
    "economy.quest.streak_milestone_reward_xp": "Tamamlanan her seri eşiği görevi için XP.",
    "economy.quest.effort_milestone_reward_xp": "Tamamlanan her emek eşiği görevi için XP.",
    "economy.quest.weekly_ritual_reward_xp": "Tamamlanan her haftalık ritüel görevi için XP.",
    "economy.quest.weekly_allowance_reward_coin": "Haftalık emek hakkı görevinin Coin'i. Ücretsiz kademenin kazandığı AI hakkı musluğu.",
    "economy.quest.weekly_allowance_active_days_target": "Haftalık emek hakkı için ISO haftasında gereken aktif gün.",
    "economy.quest.weekly_focus_sessions_target": "Haftalık odak görevi için gereken bitmiş seans.",
    "economy.quest.weekly_plan_tasks_target": "Haftalık plan görevi için gereken bitmiş plan işi.",
    "economy.quest.disabled_ids": "Virgülle ayrılmış görev kimlikleri. Listenen görev gizlenir ve hak düşmez.",
    "economy.coin.ai_chat_cost": "Ücretsiz kazançlı hak yolunda bir koç sohbeti mesajının Coin maliyeti.",
    "economy.coin.streak_freeze_cost": "Kırılan seriyi o günü dondurarak kurtarmanın Coin maliyeti.",
    "economy.coin.deep_analysis_cost": "Bir haftalık derin analiz anlatımının Coin maliyeti. Premium dahil ücretsizdir.",
    "forum.xp.accepted_answer": "Forum cevabı kabul edilince yazara verilen XP.",
    "forum.xp.thread_posted": "Forum gönderisi yazınca verilen XP. Emek panosuna gider, günlük tavanı var.",
    "forum.xp.thread_posted_daily_cap": "Günde XP kazandıran en fazla gönderi sayısı.",
    "forum.discovery.trending_window_hours": "Trend akışının baktığı hareket penceresi, saat.",
    "forum.discovery.top_window_days": "En iyiler akışının baktığı hareket penceresi, gün.",
    "forum.discovery.edit_window_minutes": "Sahibin tartışmayı veya iletisini düzenleyebileceği dakika. Dokunulmazsa kilitlenir.",
    "forum.discovery.featured_default_days": "Elle öne çıkarılan tartışmanın varsayılan ömrü, gün.",
    "forum.discovery.score.participant_weight": "Trend/en iyi skorunda her benzersiz katılımcının ağırlığı.",
    "forum.discovery.score.reaction_weight": "Trend/en iyi skorunda her olumlu tepkinin ağırlığı.",
    "forum.discovery.score.bookmark_weight": "Trend/en iyi skorunda her kaydın ağırlığı.",
    "forum.discovery.score.helpful_weight": "Trend/en iyi skorunda her faydalı oyun ağırlığı.",
    "forum.discovery.score.accepted_answer_bonus": "Kabul edilmiş cevabı olan soruya ek skor.",
    "forum.discovery.score.unanswered_question_bonus": "Henüz cevabı olmayan soruya küçük ek skor.",
    "ai.chat.daily_limit": "Premium kullanıcının günde gönderebileceği koç sohbeti sayısı.",
    "ai.plan_draft.daily_limit": "Premium kullanıcının günde üretebileceği AI plan taslağı.",
    "ai.chat.free_coin_daily_limit": "Ücretsiz kullanıcının Coin ile günde gönderebileceği koç sohbeti. Premium tavanı ayrı.",
    "ai.coach.history_max_messages": "Aktif koç dizisinden prompta alınan en fazla kayıtlı mesaj.",
    "ai.coach.history_max_characters": "Aktif dizi geçmişinden prompta alınan en fazla karakter.",
    "ai.coach.memory.transient_ttl_days": "Geçici zorluk ve öncelikli konu belleklerinin gün cinsinden ömrü.",
    "ai.photo.monthly_limit": "Premium kullanıcının 30 günde yapabileceği fotoğraf-konu sınıflandırması.",
    "ai.budget.monthly_cap_usd_cents": "Aylık AI tavanı, ABD senti. 0 tavan yok. Aşılırsa ay sonuna kadar tüm AI durur.",
    "ai.budget.reservation_usd_cents": "Her sağlayıcı çağrısında tutulan temkinli bütçe, ABD senti. En pahalı çağrıdan yüksek tut.",
    "coaching.session.min_focus_seconds": "Seansın seri, XP görevi ve emek eşiğine sayılması için gereken net odak saniyesi.",
    "coaching.weekly_recap.ready_mock_exam_count": "Haftalık özetin hazır sayılması için bitmiş haftadaki deneme sayısı.",
    "coaching.weekly_recap.ready_session_count": "Haftalık özetin hazır sayılması için gereken nitelikli odak seansı.",
    "coaching.weekly_recap.ready_plan_task_count": "Haftalık özetin hazır sayılması için gereken bitmiş plan işi.",
    "coaching.weekly_recap.comparison_min_focus_minutes_delta": "Haftalık karşılaştırmada öne çıkacak asgari odak dakikası artışı.",
    "coaching.weekly_recap.comparison_min_longest_session_minutes_delta": "Haftalık karşılaştırmada öne çıkacak asgari en uzun seans artışı, dakika.",
    "coaching.weekly_recap.comparison_min_active_days_delta": "Haftalık karşılaştırmada öne çıkacak asgari aktif gün artışı.",
    "coaching.weekly_recap.comparison_min_plan_tasks_delta": "Haftalık karşılaştırmada öne çıkacak asgari bitmiş iş artışı.",
    "coaching.weekly_recap.title_rhythm_run_days": "Time Bender unvanı için gereken ardışık aktif gün.",
    "coaching.weekly_recap.title_deep_focus_minutes": "Nebula Diver unvanı için gereken en uzun nitelikli odak, dakika.",
    "coaching.weekly_recap.title_plan_task_count": "Route Architect unvanı için gereken bitmiş plan işi.",
    "coaching.weekly_recap.title_focused_subject_count": "Dimension Explorer unvanı için gereken, taksonomide doğrulanmış odak konu.",
    "coaching.weekly_recap.title_mock_exam_count": "Phoenix Pilot unvanı için gereken deneme.",
    "coaching.weekly_recap.title_balanced_channel_count": "Cosmic Maestro unvanı için gereken kanıt kanalı.",
    "ai.features.coach.chat.free_enabled": "Ücretsiz kullanıcıya sınırlı koç sohbeti tadımı verir.",
    "ai.features.coach.chat.free_limit": "Tadım açıkken ücretsiz kullanıcının günlük koç sohbeti sayısı.",
    "ai.features.photo.categorize.free_enabled": "Ücretsiz kullanıcıya sınırlı fotoğraf-konu sınıflandırması tadımı verir.",
    "ai.features.photo.categorize.free_limit": "Tadım açıkken ücretsiz kullanıcının 30 günde sınıflandırma hakkı.",
    "ai.features.plan.ai.free_enabled": "Ücretsiz kullanıcıya sınırlı AI plan taslağı tadımı verir.",
    "ai.features.plan.ai.free_limit": "Tadım açıkken ücretsiz kullanıcının günlük plan AI çağrısı.",
    "ai.features.mood.reflection.free_enabled": "Ücretsiz kullanıcıya sınırlı ruh hali AI yansıması tadımı verir.",
    "ai.features.mood.reflection.free_limit": "Tadım açıkken ücretsiz kullanıcının günlük ruh hali yansıması.",
    "ai.features.ghost.narration.free_enabled": "Ücretsiz kullanıcıya sınırlı hayalet AI anlatımı tadımı verir.",
    "ai.features.ghost.narration.free_limit": "Tadım açıkken ücretsiz kullanıcının günlük hayalet anlatımı.",
    "ai.features.vision.note.free_enabled": "Ücretsiz kullanıcıya sınırlı vizyon tahtası AI notu tadımı verir.",
    "ai.features.vision.note.free_limit": "Tadım açıkken ücretsiz kullanıcının günlük vizyon notu.",
    "ai.features.session.reflection.free_enabled": "Ücretsiz kullanıcıya sınırlı seans AI yansıması tadımı verir.",
    "ai.features.session.reflection.free_limit": "Tadım açıkken ücretsiz kullanıcının günlük seans yansıması.",
    "ai.features.weekly.narration.free_enabled": "Ücretsiz kullanıcıya sınırlı haftalık AI anlatımı tadımı verir.",
    "ai.features.weekly.narration.free_limit": "Tadım açıkken ücretsiz kullanıcının 7 günde haftalık anlatım hakkı.",
    "ai.features.mentorship.brief.free_enabled": "Pro'suz koça sınırlı öğrenci brifi tadımı verir. Maliyet koça yazılır.",
    "ai.features.mentorship.brief.free_limit": "Tadım açıkken koçun günlük öğrenci brifi. Öğrenciye değil koça fatura edilir.",
    "ai.features.mentorship.cohort_brief.free_enabled": "Pro'suz koça sınırlı kadro brifi tadımı verir. Koç Pro'nun somut karşılığıdır, varsayılan kapalı.",
    "ai.features.mentorship.cohort_brief.free_limit": "Tadım açıkken koçun günlük kadro brifi. Bir çağrı tüm kadroyu kapsar.",
    "ai.features.mentorship.suggestions.free_enabled": "Pro'suz koça sınırlı AI ödev taslağı tadımı verir. Görevi yine koç gönderir.",
    "ai.features.mentorship.suggestions.free_limit": "Tadım açıkken koçun günlük öneri seti. Önbellek yok, yeniden çekim bu sayıya bağlı.",
    "ai.features.daily.greeting.free_enabled": "Ücretsiz kullanıcıya sınırlı günlük AI selamı tadımı verir.",
    "ai.features.daily.greeting.free_limit": "Tadım açıkken ücretsiz kullanıcının günlük selam hakkı.",
    "ai.features.deep.analysis.free_enabled": "Ücretsiz kullanıcıya Coin'siz sınırlı derin analiz tadımı verir.",
    "ai.features.deep.analysis.free_limit": "Tadım açıkken ücretsiz kullanıcının 7 günde derin analiz hakkı.",
};

export function configHint(key: string, fallback: string): string {
    return CONFIG_HINTS[key] ?? fallback;
}
