// AUTO-GENERATED by scripts/build-turkey-map.mjs — do not edit by hand.
// Regenerate with: pnpm --filter @mentor/web build:map
//
// PLACEHOLDER: empty until apps/web/data/tr-provinces.geo.json is added and the script is run.
// An empty map is a supported state, not a broken one — the province <select> is the accessible
// selection path either way, so the goal screen stays fully usable and simply renders no drawing.

export interface ProvinceShape {
  /** SVG path data in the 1000x420 viewBox. */
  d: string;
  /** Projected centroid — where the university badge sits. */
  cx: number;
  cy: number;
}

export const MAP_VIEWBOX = "0 0 1000 420";

/** Keyed by plate code "01".."81", matching `cities.code` in the API. */
export const PROVINCES: Record<string, ProvinceShape> = {};
