/**
 * Stable, machine-readable error codes. These are the keys clients branch on AND
 * the i18n keys under `errors.*` (TR/EN). Keep in sync with the locale errors.json files.
 */
export const ErrorCode = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  // identity (W0) — module-prefixed, append-only (workstreams rule)
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_IN_USE: "AUTH_EMAIL_IN_USE",
  AUTH_USERNAME_IN_USE: "AUTH_USERNAME_IN_USE",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_VERIFICATION_EMAIL_RATE_LIMITED: "AUTH_VERIFICATION_EMAIL_RATE_LIMITED",
  AUTH_TURNSTILE_FAILED: "AUTH_TURNSTILE_FAILED",
  AUTH_ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  AUTH_AVATAR_INVALID_IMAGE: "AUTH_AVATAR_INVALID_IMAGE",
  AUTH_GOOGLE_UNAVAILABLE: "AUTH_GOOGLE_UNAVAILABLE",
  AUTH_GOOGLE_STATE_INVALID: "AUTH_GOOGLE_STATE_INVALID",
  AUTH_GOOGLE_EMAIL_UNVERIFIED: "AUTH_GOOGLE_EMAIL_UNVERIFIED",
  AUTH_GOOGLE_ACCOUNT_NOT_FOUND: "AUTH_GOOGLE_ACCOUNT_NOT_FOUND",
  // coaching (W2) — module-prefixed, append-only (workstreams rule)
  COACHING_TASK_NOT_FOUND: "COACHING_TASK_NOT_FOUND",
  COACHING_TASK_DATE_READONLY: "COACHING_TASK_DATE_READONLY",
  COACHING_SESSION_NOT_FOUND: "COACHING_SESSION_NOT_FOUND",
  COACHING_SESSION_ALREADY_CLOSED: "COACHING_SESSION_ALREADY_CLOSED",
  COACHING_MOCK_EXAM_NOT_FOUND: "COACHING_MOCK_EXAM_NOT_FOUND",
  COACHING_INVALID_SUBJECT_REF: "COACHING_INVALID_SUBJECT_REF",
  COACHING_DUPLICATE_SUBJECT_REF: "COACHING_DUPLICATE_SUBJECT_REF",
  COACHING_INVALID_MOCK_EXAM_SCORES: "COACHING_INVALID_MOCK_EXAM_SCORES",
  // content (W1) — module-prefixed, append-only (workstreams rule)
  CONTENT_EXAM_NOT_FOUND: "CONTENT_EXAM_NOT_FOUND",
  CONTENT_INVALID_NET_RULE: "CONTENT_INVALID_NET_RULE",
  CONTENT_SUBJECT_NOT_FOUND: "CONTENT_SUBJECT_NOT_FOUND",
  CONTENT_INVALID_EXAM_FAMILY: "CONTENT_INVALID_EXAM_FAMILY",
  CONTENT_ARTICLE_NOT_FOUND: "CONTENT_ARTICLE_NOT_FOUND",
  CONTENT_INVALID_ARTICLE_CATEGORY: "CONTENT_INVALID_ARTICLE_CATEGORY",
  CONTENT_EXAM_EVENT_NOT_FOUND: "CONTENT_EXAM_EVENT_NOT_FOUND",
  CONTENT_INVALID_EXAM_EVENT_TYPE: "CONTENT_INVALID_EXAM_EVENT_TYPE",
  // payments (W4) — module-prefixed, append-only (workstreams rule)
  PAYMENT_TRIAL_ALREADY_USED: "PAYMENT_TRIAL_ALREADY_USED",
  PAYMENT_ALREADY_SUBSCRIBED: "PAYMENT_ALREADY_SUBSCRIBED",
  PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
  PAYMENT_WEBHOOK_INVALID: "PAYMENT_WEBHOOK_INVALID",
  PAYMENT_PREMIUM_REQUIRED: "PAYMENT_PREMIUM_REQUIRED",
  PAYMENT_REFUND_NO_CHARGE: "PAYMENT_REFUND_NO_CHARGE",
  PAYMENT_REFUND_EXCEEDS_CHARGE: "PAYMENT_REFUND_EXCEEDS_CHARGE",
  // ai (W3) — module-prefixed, append-only (workstreams rule)
  AI_DISABLED: "AI_DISABLED",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  AI_RATE_LIMITED: "AI_RATE_LIMITED",
  AI_PHOTO_RATE_LIMITED: "AI_PHOTO_RATE_LIMITED",
  AI_PHOTO_INVALID_IMAGE: "AI_PHOTO_INVALID_IMAGE",
  // admin (W6) — module-prefixed, append-only (workstreams rule)
  ADMIN_USER_NOT_FOUND: "ADMIN_USER_NOT_FOUND",
  ADMIN_CANNOT_MODIFY_SELF: "ADMIN_CANNOT_MODIFY_SELF",
  ADMIN_CONFIG_KEY_NOT_FOUND: "ADMIN_CONFIG_KEY_NOT_FOUND",
  ADMIN_CONFIG_INVALID_VALUE: "ADMIN_CONFIG_INVALID_VALUE",
  ADMIN_ROLE_NOT_ASSIGNABLE: "ADMIN_ROLE_NOT_ASSIGNABLE",
  // economy (W6) — module-prefixed, append-only (workstreams rule)
  ECONOMY_DISABLED: "ECONOMY_DISABLED",
  ECONOMY_LIMIT_EXCEEDED: "ECONOMY_LIMIT_EXCEEDED",
  INSUFFICIENT_COIN: "INSUFFICIENT_COIN",
  INVITE_CODE_INVALID: "INVITE_CODE_INVALID",
  INVITE_SELF: "INVITE_SELF",
  INVITE_ALREADY_REDEEMED: "INVITE_ALREADY_REDEEMED",
  INVITE_ALREADY_PREMIUM: "INVITE_ALREADY_PREMIUM",
  // forum (Phase-2→MVP) — module-prefixed, append-only (workstreams rule)
  FORUM_DISABLED: "FORUM_DISABLED",
  FORUM_ZONE_NOT_FOUND: "FORUM_ZONE_NOT_FOUND",
  FORUM_THREAD_NOT_FOUND: "FORUM_THREAD_NOT_FOUND",
  FORUM_POST_NOT_FOUND: "FORUM_POST_NOT_FOUND",
  FORUM_QUESTION_TITLE_REQUIRED: "FORUM_QUESTION_TITLE_REQUIRED",
  FORUM_NOT_A_QUESTION: "FORUM_NOT_A_QUESTION",
  FORUM_ALREADY_ANSWERED: "FORUM_ALREADY_ANSWERED",
  FORUM_REPORT_NOT_FOUND: "FORUM_REPORT_NOT_FOUND",
  FORUM_ATTACHMENT_INVALID: "FORUM_ATTACHMENT_INVALID",
  // social / follow (Phase-2→MVP) — module-prefixed, append-only (workstreams rule)
  SOCIAL_CANNOT_FOLLOW_SELF: "SOCIAL_CANNOT_FOLLOW_SELF",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Map a (Nest/HTTP) status to a safe generic code. */
export function httpStatusToErrorCode(status: number): ErrorCode {
  switch (status) {
    case 400:
      return ErrorCode.BAD_REQUEST;
    case 401:
      return ErrorCode.UNAUTHORIZED;
    case 403:
      return ErrorCode.FORBIDDEN;
    case 404:
      return ErrorCode.NOT_FOUND;
    case 409:
      return ErrorCode.CONFLICT;
    case 413:
      return ErrorCode.PAYLOAD_TOO_LARGE;
    case 429:
      return ErrorCode.TOO_MANY_REQUESTS;
    case 503:
      return ErrorCode.SERVICE_UNAVAILABLE;
    default:
      return status >= 500 ? ErrorCode.INTERNAL_ERROR : ErrorCode.BAD_REQUEST;
  }
}
